export const ON_CHANGE_HANDLER = 'ON_CHANGE_HANDLER';
export const FETCH_PHOTO_ERROR = 'FETCH_PHOTO_ERROR';
export const FETCH_LIST_PHOTOS = 'FETCH_LIST_PHOTOS';
export const FETCH_MORE_PHOTOS = 'FETCH_MORE_PHOTOS';
export const FETCH_PHOTO_BY_QUERY = 'FETCH_PHOTO_BY_QUERY';